title: Seokwon Song
description: Ph.D. Student at SNU
logo: /assets/img/seokwon_0209.jpg
show_downloads: False
google_analytics:
  id: G-1HX1ER5W3D
# theme: jekyll-theme-minimal
url: https://seokwon99.github.io
branch: master
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme